### ISSUE TITLE
feature-please provide 'cancelfile' interface

### ISSUE THREAD

**Issue by chenbaggio** [HashDataInc/Gopherwood#14]
if gopherwood use oss, for performance, please provide 'cancelfile',  the caller not need to call 
close->delete flow  and just call cancelfile is ok while transaction is break

imply: the cancelfile would call oss cancelfile , please refer to oss

**Comment by Eric5553** [comment]
implemented in https://github.com/HashDataInc/Gopherwood/commit/4b6a8f8e51dcc513cfc43cec1bb02cdf7cc53d12
