### ISSUE TITLE
bug-gwSeek seems only support  SEEK_SET and return value is not the current offset from file begin

### ISSUE THREAD

**Issue by chenbaggio** [HashDataInc/Gopherwood#15]
gwSeek definition is:

int gwSeek(gopherwoodFS fs, gwFile file, tOffset desiredPos);

(1) seems can not apply to SEEK_END and SEEK_CUR 
(2)  return value is not the current offset from file begin, maybe caller would rewrite calling code

**Comment by Eric5553** [comment]
gwSeek in master support both SEEK_SET/SEEK_CUR/SEEK_END
