### ISSUE TITLE
[BUG]. should check the config  value when init the context

### ISSUE THREAD

**Issue by neuyilan** [HashDataInc/Gopherwood#40]
`gopherwoodFS gwCreateContext(char *workDir, GWContextConfig *config) {
    LOG(Gopherwood::Internal::INFO, "------------------gwCreateContext start------------------");
    gopherwoodFS retVal = NULL;

    if (config != NULL) {
        Configuration::NUMBER_OF_BLOCKS = config->numBlocks;
        Configuration::LOCAL_BUCKET_SIZE = config->blockSize;
        Configuration::CUR_CONNECTION = config->numPreDefinedConcurrency;
    }`

when init the context, should check the config value is NULL or not, if the config.* is null, then the context will be in a wrong status.

**Comment by Eric5553** [comment]
fixed in https://github.com/HashDataInc/Gopherwood/commit/e67d28b158be315b663b9dfccd178a31086b4fe2
