### ISSUE TITLE
[ERROR]1. OssBlockWorker::writeBlock should check the endOfLocalSpace. 2. open too  many files error

### ISSUE THREAD

**Issue by neuyilan** [HashDataInc/Gopherwood#48]
1. when evict block to oss, should check whether the evicted block is the last bucket of the local space, if it is the last bucket of the local space, it size may not equal BUCKET_SIZE;

2. when open->write->close the file many times, the gopherwood may throw the error that "too many files open", maybe some file descriptor is not closed;

**Comment by Eric5553** [comment]
fixed

**Comment by Eric5553** [comment]
https://github.com/HashDataInc/Gopherwood/commit/5934b5ed83e185ddae089770f333364e1d15774c

fixed
